type Query {}


type Mutation {
    deleteVideo( video_id: ID! ): Response!
}

type Response {
    status: Int!
    message: String!
    data: Video
}

type Video {
    user_id: ID!
    video_id: ID!
    video_title: String!
    video_link: String!
    video_type: String!
    video_date: String!
    video_size: String!
    video_created_at: String!
}